### ISSUE TITLE
Parsing large files is slow

### ISSUE THREAD

**Issue by qzed** [DavidPfander-UniStuttgart/jsoncpp#1]
Parsing large files (or at least files containing large arrays) is slow. The attached file (1.7MiB unzipped) takes approximately 30 seconds on my notebook.

[large.zip](https://github.com/DavidPfander-UniStuttgart/jsoncpp/files/1177349/large.zip)

**Comment by DavidPfander-UniStuttgart** [comment]
Although it took me a while, I fixed the underlying performance issue. The file is now read in ~0,2s. Thanks for reporting this issue.
